import { Component, OnInit } from '@angular/core';
import { Form, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { StorageService } from 'src/app/core/services/storage.service';
import { filter, map } from 'rxjs/operators';
import { Router } from '@angular/router';

@Component({
  selector: 'app-insulator-data',
  templateUrl: './insulator-data.component.html',
  styleUrls: ['./insulator-data.component.scss'],
})
export class InsulatorDataComponent implements OnInit {
  form: FormGroup;

  electricCharge = null;
  creepageDistance = null;
  step = null;
  diameter = null;
  TF_Dry = null;
  TF_Rain = null;
  TF_Ray = null;
  insulatorWeight = null;

  insulatorCodeList = [];

  insulatorList = [
    {
      name: 'Esférico',
      id: 1,
      codes: [
        {
          id: 1,
          name: 'E-40R-120',
          electricCharge: 4000,
          creepageDistance: 215,
          step: 120,
          diameter: 175,
          TF_Dry: 40,
          TF_Rain: 32,
          TF_Ray: 70,
          insulatorWeight: 2.3,
        },
        {
          id: 2,
          name: 'E-70R-146',
          electricCharge: 7000,
          creepageDistance: 300,
          step: 146,
          diameter: 255,
          TF_Dry: 60,
          TF_Rain: 45,
          TF_Ray: 95,
          insulatorWeight: 4.1,
        },
        {
          id: 3,
          name: 'E-100R-146',
          electricCharge: 10000,
          creepageDistance: 300,
          step: 146,
          diameter: 255,
          TF_Dry: 60,
          TF_Rain: 45,
          TF_Ray: 95,
          insulatorWeight: 4.5,
        },
        {
          id: 4,
          name: 'E-120R-146',
          electricCharge: 12000,
          creepageDistance: 300,
          step: 146,
          diameter: 255,
          TF_Dry: 60,
          TF_Rain: 45,
          TF_Ray: 95,
          insulatorWeight: 4.5,
        },
      ],
    },
    {
      name: 'Estándar',
      id: 2,
      codes: [
        {
          id: 1,
          name: 'E-40-100',
          electricCharge: 4000,
          creepageDistance: 190,
          step: 110,
          diameter: 175,
          TF_Dry: 50,
          TF_Rain: 32,
          TF_Ray: 70,
          insulatorWeight: 1.7,
        },
        {
          id: 2,
          name: 'E-40-110',
          electricCharge: 4000,
          creepageDistance: 190,
          step: 110,
          diameter: 175,
          TF_Dry: 50,
          TF_Rain: 32,
          TF_Ray: 70,
          insulatorWeight: 1.7,
        },
        {
          id: 3,
          name: 'E-40E-110',
          electricCharge: 4000,
          creepageDistance: 320,
          step: 110,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.3,
        },
        {
          id: 4,
          name: 'E-70-127',
          electricCharge: 7000,
          creepageDistance: 320,
          step: 127,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.4,
        },
        {
          id: 5,
          name: 'E-70-146',
          electricCharge: 7000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.4,
        },
        {
          id: 6,
          name: 'E-100-127',
          electricCharge: 10000,
          creepageDistance: 320,
          step: 127,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.8,
        },
        {
          id: 7,
          name: 'E-100-146',
          electricCharge: 10000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.8,
        },
        {
          id: 8,
          name: 'E-120-146',
          electricCharge: 12000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.9,
        },
        {
          id: 9,
          name: 'E-160-146',
          electricCharge: 16000,
          creepageDistance: 380,
          step: 146,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 5.9,
        },
        {
          id: 10,
          name: 'E-160-170',
          electricCharge: 16000,
          creepageDistance: 380,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 6,
        },
        {
          id: 11,
          name: 'E-210-170',
          electricCharge: 21000,
          creepageDistance: 390,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 7.5,
        },
        {
          id: 12,
          name: 'E-240-170',
          electricCharge: 24000,
          creepageDistance: 380,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 7.7,
        },
        {
          id: 13,
          name: 'E-300-195',
          electricCharge: 30000,
          creepageDistance: 485,
          step: 195,
          diameter: 330,
          TF_Dry: 85,
          TF_Rain: 50,
          TF_Ray: 130,
          insulatorWeight: 10.8,
        },
        {
          id: 14,
          name: 'E-400-205',
          electricCharge: 40000,
          creepageDistance: 550,
          step: 205,
          diameter: 360,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 14,
        },
        {
          id: 15,
          name: 'F70/127',
          electricCharge: 7000,
          creepageDistance: 320,
          step: 127,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.6,
        },
        {
          id: 16,
          name: 'F70/146',
          electricCharge: 7000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.6,
        },
        {
          id: 17,
          name: 'F100/127',
          electricCharge: 10000,
          creepageDistance: 320,
          step: 127,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 3.9,
        },
        {
          id: 18,
          name: 'F100/146',
          electricCharge: 10000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 4,
        },
        {
          id: 19,
          name: 'F12/127',
          electricCharge: 12000,
          creepageDistance: 320,
          step: 127,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 4,
        },
        {
          id: 20,
          name: 'F12/146',
          electricCharge: 12000,
          creepageDistance: 320,
          step: 146,
          diameter: 255,
          TF_Dry: 70,
          TF_Rain: 40,
          TF_Ray: 100,
          insulatorWeight: 4,
        },
        {
          id: 21,
          name: 'F16/146',
          electricCharge: 16000,
          creepageDistance: 380,
          step: 146,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 6,
        },
        {
          id: 22,
          name: 'F160/170',
          electricCharge: 16000,
          creepageDistance: 380,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 6.5,
        },
        {
          id: 23,
          name: 'F21/170',
          electricCharge: 21000,
          creepageDistance: 380,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 7.2,
        },
        {
          id: 24,
          name: 'F24/170',
          electricCharge: 24000,
          creepageDistance: 380,
          step: 170,
          diameter: 280,
          TF_Dry: 75,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 7.5,
        },
        {
          id: 25,
          name: 'F300/195',
          electricCharge: 30000,
          creepageDistance: 480,
          step: 195,
          diameter: 320,
          TF_Dry: 85,
          TF_Rain: 50,
          TF_Ray: 130,
          insulatorWeight: 10.9,
        },
        {
          id: 26,
          name: 'F400/205',
          electricCharge: 40000,
          creepageDistance: 550,
          step: 205,
          diameter: 360,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 14,
        },
        {
          id: 27,
          name: 'F530/240',
          electricCharge: 53000,
          creepageDistance: 620,
          step: 240,
          diameter: 360,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 18,
        },
        {
          id: 28,
          name: 'F760/270',
          electricCharge: 76000,
          creepageDistance: 680,
          step: 270,
          diameter: 400,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 145,
          insulatorWeight: 26.1,
        },
      ],
    },
    {
      name: 'Anticontaminación',
      id: 3,
      codes: [
        {
          id: 1,
          name: 'E-70P-127',
          electricCharge: 7000,
          creepageDistance: 390,
          step: 127,
          diameter: 255,
          TF_Dry: 80,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 4.6,
        },
        {
          id: 2,
          name: 'E-70P-146',
          electricCharge: 7000,
          creepageDistance: 390,
          step: 146,
          diameter: 255,
          TF_Dry: 80,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 4.6,
        },
        {
          id: 3,
          name: 'E-70PP-146',
          electricCharge: 7000,
          creepageDistance: 445,
          step: 146,
          diameter: 280,
          TF_Dry: 85,
          TF_Rain: 50,
          TF_Ray: 125,
          insulatorWeight: 5.6,
        },
        {
          id: 4,
          name: 'E-100P-127',
          electricCharge: 10000,
          creepageDistance: 390,
          step: 127,
          diameter: 255,
          TF_Dry: 80,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 4.7,
        },
        {
          id: 5,
          name: 'E-100P-146',
          electricCharge: 10000,
          creepageDistance: 390,
          step: 146,
          diameter: 255,
          TF_Dry: 80,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 4.7,
        },
        {
          id: 6,
          name: 'E-100PP-146',
          electricCharge: 10000,
          creepageDistance: 445,
          step: 146,
          diameter: 280,
          TF_Dry: 85,
          TF_Rain: 50,
          TF_Ray: 125,
          insulatorWeight: 5.6,
        },
        {
          id: 7,
          name: 'E-120P-146',
          electricCharge: 12000,
          creepageDistance: 390,
          step: 146,
          diameter: 255,
          TF_Dry: 80,
          TF_Rain: 45,
          TF_Ray: 110,
          insulatorWeight: 4.8,
        },
        {
          id: 8,
          name: 'E-120PP-146',
          electricCharge: 12000,
          creepageDistance: 445,
          step: 146,
          diameter: 280,
          TF_Dry: 85,
          TF_Rain: 50,
          TF_Ray: 125,
          insulatorWeight: 5.7,
        },
        {
          id: 9,
          name: 'E-120PG-146',
          electricCharge: 12000,
          creepageDistance: 555,
          step: 146,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 9.2,
        },
        {
          id: 10,
          name: 'E-160P-146',
          electricCharge: 16000,
          creepageDistance: 555,
          step: 146,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 9.2,
        },
        {
          id: 11,
          name: 'E-160P-170',
          electricCharge: 16000,
          creepageDistance: 555,
          step: 170,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 9.3,
        },
        {
          id: 12,
          name: 'E-210P-170',
          electricCharge: 21000,
          creepageDistance: 550,
          step: 170,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 10.2,
        },
        {
          id: 13,
          name: 'E-240P-170',
          electricCharge: 24000,
          creepageDistance: 550,
          step: 170,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 10.4,
        },
        {
          id: 14,
          name: 'E-300P-195',
          electricCharge: 30000,
          creepageDistance: 600,
          step: 195,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 50,
          TF_Ray: 135,
          insulatorWeight: 12,
        },
        {
          id: 15,
          name: 'F9P-A/146',
          electricCharge: 10000,
          creepageDistance: 390,
          step: 146,
          diameter: 255,
          TF_Dry: 72,
          TF_Rain: 42,
          TF_Ray: 110,
          insulatorWeight: 4.6,
        },
        {
          id: 16,
          name: 'F100P/146',
          electricCharge: 10000,
          creepageDistance: 445,
          step: 146,
          diameter: 280,
          TF_Dry: 80,
          TF_Rain: 50,
          TF_Ray: 125,
          insulatorWeight: 5.8,
        },
        {
          id: 17,
          name: 'F100PF/146',
          electricCharge: 10000,
          creepageDistance: 545,
          step: 146,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 8.9,
        },
        {
          id: 18,
          name: 'F12P-A/146',
          electricCharge: 12000,
          creepageDistance: 390,
          step: 146,
          diameter: 255,
          TF_Dry: 72,
          TF_Rain: 42,
          TF_Ray: 110,
          insulatorWeight: 4.6,
        },
        {
          id: 19,
          name: 'F120P/146',
          electricCharge: 12000,
          creepageDistance: 445,
          step: 146,
          diameter: 280,
          TF_Dry: 80,
          TF_Rain: 50,
          TF_Ray: 125,
          insulatorWeight: 5.8,
        },
        {
          id: 20,
          name: 'F160P/146',
          electricCharge: 16000,
          creepageDistance: 545,
          step: 146,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 8.8,
        },
        {
          id: 21,
          name: 'F160P/170',
          electricCharge: 16000,
          creepageDistance: 545,
          step: 170,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 8.9,
        },
        {
          id: 22,
          name: 'F210P/170',
          electricCharge: 21000,
          creepageDistance: 550,
          step: 170,
          diameter: 330,
          TF_Dry: 90,
          TF_Rain: 55,
          TF_Ray: 140,
          insulatorWeight: 10.2,
        },
        {
          id: 23,
          name: 'F300P/195',
          electricCharge: 30000,
          creepageDistance: 690,
          step: 195,
          diameter: 380,
          TF_Dry: 100,
          TF_Rain: 55,
          TF_Ray: 150,
          insulatorWeight: 15.3,
        },
        {
          id: 24,
          name: 'F30P/195',
          electricCharge: 30000,
          creepageDistance: 595,
          step: 195,
          diameter: 320,
          TF_Dry: 90,
          TF_Rain: 50,
          TF_Ray: 135,
          insulatorWeight: 11.1,
        },
      ],
    },
    {
      name: 'Aerodinámico',
      id: 4,
      codes: [
        {
          id: 1,
          name: 'E-70D-127',
          electricCharge: 7000,
          creepageDistance: 350,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.7,
        },
        {
          id: 2,
          name: 'E-70DP-127',
          electricCharge: 7000,
          creepageDistance: 365,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.7,
        },
        {
          id: 3,
          name: 'E-100D-127',
          electricCharge: 10000,
          creepageDistance: 350,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 4,
          name: 'E-100DP-127',
          electricCharge: 10000,
          creepageDistance: 365,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 5,
          name: 'E-120D-127',
          electricCharge: 12000,
          creepageDistance: 350,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 6,
          name: 'E-120DP-127',
          electricCharge: 12000,
          creepageDistance: 365,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 8,
          name: 'E-120DP-146',
          electricCharge: 12000,
          creepageDistance: 365,
          step: 146,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.7,
        },
        {
          id: 9,
          name: 'E-160D-146',
          electricCharge: 16000,
          creepageDistance: 350,
          step: 146,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 95,
          insulatorWeight: 6.4,
        },
        {
          id: 10,
          name: 'E-160GD-146',
          electricCharge: 16000,
          creepageDistance: 375,
          step: 146,
          diameter: 420,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 95,
          insulatorWeight: 7.1,
        },
        {
          id: 11,
          name: 'E-210GD-170',
          electricCharge: 21000,
          creepageDistance: 375,
          step: 170,
          diameter: 420,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 8.9,
        },
        {
          id: 12,
          name: 'F100D/127',
          electricCharge: 10000,
          creepageDistance: 365,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 13,
          name: 'F12D/127',
          electricCharge: 12000,
          creepageDistance: 365,
          step: 127,
          diameter: 380,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 5.6,
        },
        {
          id: 14,
          name: 'F160D/146',
          electricCharge: 16000,
          creepageDistance: 375,
          step: 146,
          diameter: 420,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 8,
        },
        {
          id: 15,
          name: 'F21D/170',
          electricCharge: 21000,
          creepageDistance: 370,
          step: 170,
          diameter: 420,
          TF_Dry: 60,
          TF_Rain: 50,
          TF_Ray: 90,
          insulatorWeight: 8.9,
        },
      ]
    }
  ];

  constructor(
    private fb: FormBuilder,
    private readonly storageService: StorageService,
    private readonly router: Router
  ) {
    this.form = this.fb.group({
      insulatorTypeId: [null, [Validators.required]],
      insulatorCodeId: [null, [Validators.required]],

      electricCharge: [null, [Validators.required]],
      creepageDistance: [null, [Validators.required]],
      step: [null, [Validators.required]],
      diameter: [null, [Validators.required]],
      TF_Dry: [null, [Validators.required]],
      TF_Rain: [null, [Validators.required]],
      TF_Ray: [null, [Validators.required]],
      insulatorWeight: [null, [Validators.required]],
    });

 
    this.form.get('insulatorTypeId').valueChanges.subscribe((data) => {
      this.insulatorCodeList = this.insulatorList.find(
        (t) => t.id == data
      ).codes;

      this.form.patchValue({
        insulatorCodeId: null,
        electricCharge: null,
        creepageDistance: null,
        step: null,
        diameter: null,
        TF_Dry: null,
        TF_Rain: null,
        TF_Ray: null,
        insulatorWeight: null,
      });
    });

    this.form
      .get('insulatorCodeId')
      .valueChanges.pipe(filter((x) => x))
      .subscribe((data) => {
        /*
         * Ahora encontramos donde se encuentra los valores faltantes
         */
        const foundMatchinCodeWithData = this.insulatorList
          .find((t) => t.id == this.form.get('insulatorTypeId').value)
          .codes.find((m) => m.id == data);

        this.form.patchValue({
          electricCharge: foundMatchinCodeWithData.electricCharge,
          creepageDistance: foundMatchinCodeWithData.creepageDistance,
          step: foundMatchinCodeWithData.step,
          diameter: foundMatchinCodeWithData.diameter,
          TF_Dry: foundMatchinCodeWithData.TF_Dry,
          TF_Rain: foundMatchinCodeWithData.TF_Rain,
          TF_Ray: foundMatchinCodeWithData.TF_Ray,
          insulatorWeight: foundMatchinCodeWithData.insulatorWeight,
        });
      });

      this.storageService.insulatorData
      .pipe(
        map((data) => {
          if (data) {
            this.form.patchValue(data);
          }
        })
      )
      .subscribe();
  }

  ngOnInit() {}

  saveForm() {
    this.storageService.setInsulatorData(this.form.getRawValue());
    this.storageService.setInsulatorDataIsComplete(true);

    this.router.navigate(['/']);
  }
}
